name: Test
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16"
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          go test -race \
            -count=1 \
            -covermode=atomic \
            -coverprofile=coverage.out \
            ./...
      - uses: codecov/codecov-action@v1
        with:
          # token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.out
          verbose: true
